import "dotenv/config";
import { expect,test,type BrowserContext,type Page } from "@playwright/test";
import { Client } from "pg";
const email=process.env.SEED_ADMIN_EMAIL;const password=process.env.SEED_ADMIN_PASSWORD;if(!email||!password)throw new Error("Credenciales E2E requeridas.");
const createdIds:string[]=[];let sessionCookies:Parameters<BrowserContext["addCookies"]>[0]=[];
async function login(page:Page){await page.goto("/login");await page.getByLabel("Correo corporativo").fill(email!);await page.getByLabel("Contraseña").fill(password!);await page.getByRole("button",{name:"Iniciar sesión"}).click();await expect(page).toHaveURL(/\/dashboard/);}
async function createInspection(page:Page){await page.goto("/inspecciones/nueva");await page.getByLabel("Actividad").selectOption({index:1});await page.getByRole("button",{name:"Crear inspección"}).click();await expect(page).not.toHaveURL(/\/inspecciones\/nueva$/, { timeout: 15000 });await expect(page).toHaveURL(/\/inspecciones\/[\w-]+$/, { timeout: 15000 });const id=page.url().split("/").pop()!;createdIds.push(id);return id;}
async function completeInspection(page:Page){const buttons=page.getByRole("button",{name:"Guardar elemento"});await expect(buttons).toHaveCount(4);for(let i=0;i<4;i++){const form=buttons.nth(i).locator("xpath=..");await form.locator('select[name="compliant"]').selectOption("true");const response=page.waitForResponse(r=>r.request().method()==="POST"&&r.url().includes("/inspecciones/"));await form.getByRole("button",{name:"Guardar elemento"}).click();await response;}const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");await page.getByLabel("Agregar fotografía").setInputFiles({name:"evidencia.png",mimeType:"image/png",buffer:png});await page.getByRole("button",{name:"Cargar evidencia"}).click();await expect(page.getByRole("status")).toContainText("correctamente");await page.getByRole("button",{name:"Enviar a revisión"}).click();await expect(page.getByText("Decisión y firma del responsable SST")).toBeVisible();}
async function cookieHeader(page:Page){return(await page.context().cookies()).map(c=>`${c.name}=${c.value}`).join("; ");}
test.afterAll(async()=>{if(!createdIds.length)return;const direct=new URL(process.env.DATABASE_URL!);const ref=direct.hostname.split(".")[1];const db=new Client({host:`aws-0-${process.env.SUPABASE_REGION}.pooler.supabase.com`,port:5432,user:`postgres.${ref}`,password:decodeURIComponent(direct.password),database:"postgres",ssl:{rejectUnauthorized:false}});await db.connect();await db.query("delete from inspections where id = any($1::text[])",[createdIds]);await db.end();});
test("login, inspección, evidencia, aprobación, PDF y CSV",async({page,request})=>{await login(page);sessionCookies=await page.context().cookies();const id=await createInspection(page);await completeInspection(page);const approve=page.locator('form:has(input[value="APPROVED"])');await approve.getByPlaceholder("Justificación obligatoria").fill("Inspección conforme verificada por prueba E2E");await approve.getByRole("button",{name:"Confirmar y firmar"}).click();await expect(page.getByText("Firmas y aprobaciones")).toBeVisible();const headers={cookie:await cookieHeader(page)};const pdf=await request.get(`/api/v1/inspections/${id}/report.pdf`,{headers});expect(pdf.ok()).toBeTruthy();expect(pdf.headers()["content-type"]).toContain("application/pdf");const csv=await request.get("/api/v1/reports/inspections.csv",{headers});expect(csv.ok()).toBeTruthy();expect(csv.headers()["content-type"]).toContain("text/csv");});
test("rechazo firmado de una inspección",async({page})=>{if(sessionCookies.length){await page.context().addCookies(sessionCookies);await page.goto("/dashboard");}else await login(page);await createInspection(page);await completeInspection(page);const reject=page.locator('form:has(input[value="REJECTED"])');await reject.getByPlaceholder("Justificación obligatoria").fill("Rechazo controlado para validar la trazabilidad E2E");await reject.getByRole("button",{name:"Confirmar y firmar"}).click();await expect(page.getByText("Rechazada").first()).toBeVisible();});
