-- Align the existing Supabase enums with the Spanish values used by the application.
-- Renaming values preserves rows, defaults, indexes, and foreign dependencies.

ALTER TYPE "InspectionStatus" RENAME VALUE 'DRAFT' TO 'BORRADOR';
ALTER TYPE "InspectionStatus" RENAME VALUE 'IN_PROGRESS' TO 'EN_PROGRESO';
ALTER TYPE "InspectionStatus" RENAME VALUE 'PENDING_CORRECTION' TO 'CORRECCION_PENDIENTE';
ALTER TYPE "InspectionStatus" RENAME VALUE 'PENDING_REVIEW' TO 'PENDIENTE_REVISION';
ALTER TYPE "InspectionStatus" RENAME VALUE 'APPROVED' TO 'APROBADA';
ALTER TYPE "InspectionStatus" RENAME VALUE 'REJECTED' TO 'RECHAZADA';
ALTER TYPE "InspectionStatus" RENAME VALUE 'CANCELLED' TO 'CANCELADA';

ALTER TYPE "PpeItemStatus" RENAME VALUE 'AVAILABLE' TO 'DISPONIBLE';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'ASSIGNED' TO 'ASIGNADO';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'MAINTENANCE' TO 'MANTENIMIENTO';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'DAMAGED' TO 'DANADO';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'EXPIRED' TO 'VENCIDO';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'LOST' TO 'PERDIDO';
ALTER TYPE "PpeItemStatus" RENAME VALUE 'RETIRED' TO 'RETIRADO';

ALTER TYPE "ApprovalDecision" RENAME VALUE 'APPROVED' TO 'APROBADA';
ALTER TYPE "ApprovalDecision" RENAME VALUE 'REJECTED' TO 'RECHAZADA';
